version: '3.8'

services:
  postgres:
    image: postgres:14.2
    ports:
      - ${DB_PORT}:5432
    container_name: ${DB_NAME}
    environment:
      DB_DIALECT: ${DB_DIALECT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql
